drop table userprofile_url;
drop table userprofile_mention;
drop table userprofile_hashtag;
drop table userprofile_media;
drop table userprofile_tickersymbol;
drop table tweet_tickersymbol;
drop table tweet_mention;
drop table tweet_media;
drop table tweet_hashtag;
drop table tweet_url;
drop table url_cache;
-- drop table url_indices;
drop table url;
-- drop table tickersymbol_indices;
drop table tickersymbol;
-- drop table mention_indices;
drop table mention;
-- drop table media_indices;
drop table media;
-- drop table hashtag_indices;
drop table hashtag;
drop table tweet;
drop table userprofile;
drop table task_history;
drop table task;
drop sequence hibernate_sequence;
