#!/opt/local/bin/bash

echo "------------------------------------------"
export TWITTERWALL_FRONTEND_MAX_RESULTS=60
export TWITTERWALL_SHOW_USERS_MENU=true
export TWITTER_PAGE_SIZE=500
export TWITTER_FETCH_TESTDATA=false
export TWITTERWALL_WAIT_FOR_TEST=20000
export TWITTERWALL_URL_TEST_DATA_VERBOSE=true
export TWITTERWALL_SCHEDULER_ALLOW_UPDATE_TWEETS=false
export TWITTERWALL_SCHEDULER_ALLOW_UPDATE_USERS=false
export TWITTERWALL_SCHEDULER_ALLOW_SEARCH=true
export TWITTER_SEARCH_TERM='#hibernate OR #java OR #TYPO3'
export TWITTERWALL_INFO_WEBPAGE=https://github.com/phasenraum2010/twitterwall2
export TWITTERWALL_THEME=typo3
export TWITTERWALL_APP_NAME='Twitterwall'
echo "------------------------------------------"
echo "TWITTERWALL_FRONTEND_MAX_RESULTS $TWITTERWALL_FRONTEND_MAX_RESULTS"
echo "TWITTERWALL_SHOW_USERS_MENU $TWITTERWALL_SHOW_USERS_MENU"
echo "TWITTER_PAGE_SIZE $TWITTER_PAGE_SIZE"
echo "TWITTER_FETCH_TESTDATA $TWITTER_FETCH_TESTDATA"
echo "TWITTERWALL_WAIT_FOR_TEST $TWITTERWALL_WAIT_FOR_TEST"
echo "TWITTERWALL_URL_TEST_DATA_VERBOSE $TWITTERWALL_URL_TEST_DATA_VERBOSE"
echo "TWITTERWALL_SCHEDULER_ALLOW_UPDATE_TWEETS $TWITTERWALL_SCHEDULER_ALLOW_UPDATE_TWEETS"
echo "TWITTERWALL_SCHEDULER_ALLOW_UPDATE_USERS $TWITTERWALL_SCHEDULER_ALLOW_UPDATE_USERS"
echo "TWITTERWALL_SCHEDULER_ALLOW_SEARCH $TWITTERWALL_SCHEDULER_ALLOW_SEARCH"
echo "TWITTER_SEARCH_TERM $TWITTER_SEARCH_TERM"
echo "TWITTERWALL_INFO_WEBPAGE $TWITTERWALL_INFO_WEBPAGE"
echo "TWITTERWALL_THEME $TWITTERWALL_THEME"
echo "TWITTERWALL_APP_NAME $TWITTERWALL_APP_NAME"
echo "------------------------------------------"