package org.woehlke.twitterwall.oodm.entities.parts;

/**
 * Created by tw on 09.07.17.
 */
public enum TaskType {

    NULL,
    FETCH_TWEETS_FROM_SEARCH,
    FETCH_USERS_FROM_LIST,
    FETCH_FOLLOWER,
    UPDATE_TWEETS,
    UPDATE_USERS,
    UPDATE_USERS_FROM_MENTIONS,
    CONTROLLER_CREATE_IMPRINT_USER,
    CONTROLLER_CREATE_TESTDATA_TWEETS,
    CONTROLLER_CREATE_TESTDATA_USERS,
    CONTROLLER_ADD_USER_FOR_SCREEN_NAME,
    REMOVE_OLD_DATA_FROM_STORAGE
}
