package org.woehlke.twitterwall.oodm.entities.parts;

/**
 * Created by tw on 09.07.17.
 */
public enum TaskType {

    NULL,
    FETCH_TWEETS_FROM_SEARCH,
    FETCH_HOME_TIMELINE,
    FETCH_USER_TIMELINE,
    FETCH_MENTIONS,
    FETCH_FAVORITES,
    FETCH_RETWEETS_OF_ME,
    FETCH_LISTS,
    FETCH_USERS_FROM_LIST,
    FETCH_USERLIST_OWNERS,
    FETCH_FOLLOWER,
    FETCH_FRIENDS,
    UPDATE_TWEETS,
    UPDATE_USERS,
    UPDATE_USERS_FROM_MENTIONS,
    CONTROLLER_CREATE_IMPRINT_USER,
    CONTROLLER_CREATE_TESTDATA_TWEETS,
    CONTROLLER_CREATE_TESTDATA_USERS,
    CONTROLLER_ADD_USER_FOR_SCREEN_NAME,
    REMOVE_OLD_DATA_FROM_STORAGE,
    GARBAGE_COLLECTION
}
