
twitterwall:
  frontend:
    info:
      webpage: ${TWITTERWALL_INFO_WEBPAGE}
    theme: ${TWITTERWALL_THEME}
        maxResults: ${TWITTERWALL_FRONTEND_MAX_RESULTS}
        menu:
            appname: ${TWITTERWALL_APP_NAME}
        imprint:
            screenName: ${TWITTERWALL_INFO_IMPRINT_SCREEN_NAME}
            subtitle: "www.natural-born-coder.de <br/> twitterwall-port80guru.herokuapp.com"
        idGoogleAnalytics: ${TWITTERWALL_GOOGLE_ANALYTICS_ID}
    scheduler:
        allowUpdateTweets: ${TWITTERWALL_SCHEDULER_ALLOW_UPDATE_TWEETS}
        allowUpdateUserProfiles: ${TWITTERWALL_SCHEDULER_ALLOW_UPDATE_USERS}
        allowUpdateUserProfilesFromMention: ${TWITTERWALL_SCHEDULER_ALLOW_UPDATE_USERS_FROM_MENTION}
        allowFetchTweetsFromTwitterSearch: ${TWITTERWALL_SCHEDULER_ALLOW_SEARCH}
        herokuDbRowsLimit: ${TWITTERWALL_SCHEDULER_HEROKU_DB_LIMIT}
        skipFortesting: true
        fetchUserList:
            name: ${TWITTERWALL_SCHEDULER_USER_LIST_NAME}
            allow: ${TWITTERWALL_SCHEDULER_USER_LIST_ALLOW}
    context:
        test: ${TWITTERWALL_CONTEXT_TEST}
    backend:
        twitter:
            millisToWaitForFetchTweetsFromTwitterSearch: ${TWITTERWALL_WAIT_FOR_TEST}
            millisToWaitBetweenTwoApiCalls: 5000
        url:
            fetchTestDataVerbose: ${TWITTERWALL_URL_TEST_DATA_VERBOSE}
            connTimeToLive: 10
            maxIdleTime: 120
spring:
    application:
        name: @project.name@
        admin:
            enabled: false
    mvc:
        date-format: dd.MM.yyyy
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        generate-ddl: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL94Dialect
    datasource:
        url: ${JDBC_DATABASE_URL}
        driverClassName: org.postgresql.Driver
        platform: POSTGRESQL
        maxActive: 60
        maxIdle: 5
        minIdle: 2
        initialSize: 5
        removeAbandoned: true
        max-total: 70
        tomcat:
            max-wait: 10000
            max-active: 50
            test-on-borrow: true
    thymeleaf:
        cache: false
    template:
        cache: false
    devtools:
        livereload:
            enabled: false
management:
        address: 127.0.0.1
        context-path: /manage
        security:
            enabled: false
info:
    application:
        name: @project.name@
        groupId: @project.groupId@
        artifactId: @project.artifactId@
        version: @project.version@
        description: @project.description@
endpoints:
    shutdown:
        enabled: false
    health:
        sensitive: false
    env:
        keys-to-sanitize: password,secret,key,passwort
server:
    context-path: /twitterwall2
    tomcat:
        accesslog:
            file-date-format: .yyyy-MM-dd
logging:
    file: twitterwall.log
hibernate:
    dialect: org.hibernate.dialect.PostgreSQL94Dialect
